logging:
  level:
    root: INFO

# Make sure to disable the AMQP bus loaded by root project
spring:
  cloud:
    bus:
      enabled: false

cloud:
  aws:
    credentials:
      useDefaultAwsCredentialsChain: true
    stack:
      auto: false
    region:
      static: us-east-2
      auto: false
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/538467152985/test.fifo
