---
logging:
  level:
    root: INFO

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
server:
  port: 8081

