---
logging:
  level:
    root: INFO

cloud:
  aws:
    credentials:
      useDefaultAwsCredentialsChain: true
    stack:
      auto: false
    region:
      static: us-east-2
      auto: false

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
server:
  port: 8081

